FROM node:22-alpine3.19

ENV TZ=America/Mexico_City
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

RUN npm install -g @angular/cli@19

COPY package*.json ./

RUN npm install && npm cache clean --force

ENV NODE_OPTIONS="--max_old_space_size=4096"

COPY . .

EXPOSE 4200

CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200"]