#!/bin/bash

cat <<EOF > /docker-entrypoint-initdb.d/init.sql
CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE_DEV;
CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE_TEST;
CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE_PROD;

GRANT ALL PRIVILEGES ON $MYSQL_DATABASE_DEV.* TO '$MYSQL_USER'@'%';
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE_TEST.* TO '$MYSQL_USER'@'%';
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE_PROD.* TO '$MYSQL_USER'@'%';

FLUSH PRIVILEGES;
EOF
